#!/bin/bash
export PATH=$PATH:~/dotfile/script/:
export PATH=$PATH:$HOME/.config/lsp/lua-language-server/bin
# . ~/dotfile/script/z.sh
source ~/dotfile/script/ffd
alias scr="cd ~/dotfile/script"
export FZF_TMUX=1
export FZF_TMUX_OPTS='-p80%,60%'

export BAT_THEME="Catppuccin Mocha"

# --preview 'bat --style=numbers --color=always --theme=gruvbox-dark --line-range :500 {}'
export FZF_DEFAULT_COMMAND="
		bfs -type f -exclude \( \
			-name .git \
			-or -name node_modules \
			-or -name target \
			\) 2>&1
"
export FZF_DEFAULT_OPTS="
--height=100%
--layout=reverse
--info=right
--border=thinblock
--preview 'bat --style=numbers --color=always --line-range :500 {}'
--preview-window=up:80%
--bind ctrl-d:preview-down,ctrl-u:preview-up
--bind ctrl-b:preview-bottom,ctrl-t:preview-top
--bind 'ctrl-/:change-preview-window(down|hidden|)'
--cycle
  "
export FZF_CTRL_T_OPTS="
--preview ''
"

export FZF_CTRL_R_OPTS="
--preview ''
"

export FZF_ALT_C_OPTS="
--preview ''
"

alias rng='ranger'
alias t='tmux'

alias Jc='$HOME/dotfile/script/Jc.sh'

alias aqua="$HOME/dotfile/animetion.sh"
#alias z="clear;zsh"
alias vz="nvim ~/.zshrc"
alias vv="nvim ~/.config/nvim/init.vim"
alias v='nvim'
alias pac="sudo pacman"
alias vf="vifm"
alias ju="jupyter notebook"

alias cl='clear'
alias rh='cd $PWD;python3 -m http.server --cgi 8080'
alias cf='fc-list'
alias ct="source ~/my_linux_env/bash_script/timeout.sh"
alias fp="fzf --preview 'bat --color "always" {}'"
alias mb="~/dotfile/backup"
alias vb="~/scripts/nvim_backup"
alias www='(ls -d ~/wallpapers/* | shuf -n 1 ) | xargs nitrogen --set-zoom-fill '
alias ww='(ls -d ~/wallpapers/* | shuf -n 1 ) | xargs swww img --transition-type wipe --transition-angle 30 --transition-step 90'
alias d='BROWSER=w3m ddgr'

alias weather='clear && curl wttr.in'
alias fetch='clear && fastfetch '
alias mw="(mv ~/Downloads/*.png ~/wallpapers/ 2>/dev/null | mv ~/Downloads/*.jpg ~/wallpapers/ 2>/dev/null) 2>/dev/null && echo 'move wallpaper file success!!'"

alias rng='ranger'

alias wa="sxiv -t ~/wallpapers"

alias aa="~/coding/python_project/scraping/add_anime.py $1 $2"
alias chapter="~/coding/python_project/scraping/anime_chapters.py $1 $2"
alias sa="~/coding/python_project/scraping/showanime.py; less ~/coding/python_project/scraping/anime_name.txt"
alias st="$HOME/dotfile/script/show-tmux"
alias covid="$HOME/dotfile/script/covid"
alias runpro="$SCRIPT/runpro"

alias kd="killall Discord"
alias gis="git status"
alias xml="~/dotfile/script/xml"

alias vimstartup=" rm vim.log && nvim --startuptime vim.log -c 'q' && cat vim.log | sort -nrk 3 | head -20"

alias lg=lazygit

export FZF_ALT_C_COMMAND="fd --hidden -t d . $HOME"
export FZF_CTRL_T_COMMAND="fd --hidden . $HOME"

alias newip="echo -e 'AUTHENTICATE ""\r\nsignal NEWNYM\r\nQUIT' | nc 127.0.0.1 9051"

FZF_GIT_LOG() {
	git log --oneline --format="%C(auto)%h %s%d" | fzf --ansi --preview "git show --color=always {1}" --bind 'enter:become(echo {1})'
}

FZF_GIT_DIFF() {
	git log --oneline --format="%C(auto)%h %s%d" | fzf --ansi --preview "git show --color=always {1}" --bind 'enter:become(echo {1})' | xargs -I {} git diff {}
}

FZF_GIT_STATUS() {
	git status -s | fzf --preview="git diff --color=always HEAD {2}"
}

FZF_DOCKER_PS() {
	docker ps --format="{{.ID}}\t{{.Names}}\t{{.Image}}" | fzf --preview='docker logs {1}' | awk '{print $1}'
}

FZF_TMUX_SWITCH_SESSION() {
	[[ -n "$TMUX" ]] && change="switch-client" || change="attach-session"
	if [ $1 ]; then
		tmux $change -t "$1" 2>/dev/null || (tmux new-session -d -s $1 && tmux $change -t "$1")
		return
	fi
	session=$(tmux ls | cut -d':' -f1 | fzf-tmux -p 90% --preview 'tmux list-windows -t{}' \
		--border-label 'switch session' \
		--header 'Press CTRL-R to reload, CTRL-A to add, CTRL-D to delete' \
		--bind 'ctrl-a:execute(tmux new -s {q} -d )+reload(tmux ls | cut -d ":" -f1)' \
		--bind 'ctrl-d:execute(tmux kill-ses -t {})+reload(tmux ls | cut -d ":" -f1)' \
		--bind 'ctrl-r:reload(tmux ls | cut -d ":" -f1)') &&
		tmux $change -t "$session" || echo "No sessions found."
}

FZF_CD() {
	dr=$(
		bfs -type d -exclude \( \
			-name .git \
			-or -name node_modules \
			-or -name target \
			\) 2>&1 | fzf-tmux -p 90% \
			--preview 'tree -L 2 {}' \
			--preview-window=up:60% \
			--border-label='fzf cd' # fd -td --hidden 2>/dev/null | fzf-tmux -p 90% \
	) && test $? -eq 0 && cd $dr
}

FZF_VF() {
	file=$(
		bfs -type f -exclude \( \
			-name .git \
			-or -name node_modules \
			-or -name target \
			\) 2>&1 | fzf-tmux -p 90% \
			--preview-window=up:60% \
			--border-label='fzf edit file' \
			--print0
	) && test $? -eq 0 && nvim $file
}

FZF_MISE_VERSION() {
	mise ls | fzf-tmux -p 80% \
		--preview '' \
		--bind 'ctrl-a:execute(mise use {q})+reload(mise ls)' \
		--border-label='Mise version' |
		awk '{printf "%s@%s", $1,$2}' | xargs -I _ mise use _
}

FZF_KUBE_PODS() {
	preview_cmd='kubectl describe pods {1}'
	kubectl get pods | fzf-tmux -p 90% \
		\
		--preview-window=up:80% \
		--header-lines=1 \
		--preview "$preview_cmd" \
		--bind "focus:preview-bottom" \
		--bind 'ctrl-j:down' \
		--bind 'ctrl-k:up' \
		--border-label='kube get pods' | awk '{print $1}'
}

alias gl=FZF_GIT_LOG
export PATH=$PATH:/usr/local/go/bin:$GOPATH/bin
alias gld=FZF_GIT_DIFF
alias gs=FZF_GIT_STATUS
alias dps=FZF_DOCKER_PS
alias ts=FZF_TMUX_SWITCH_SESSION
alias cdf=FZF_CD
alias vf=FZF_VF
alias msv=FZF_MISE_VERSION
alias kgp=FZF_KUBE_PODS

alias dcu="docker compose up"
alias dcd="docker compose down"
