#!/bin/bash
config=(~/.config/starship.toml, ~/.bashrc, ~/.zshrc, ~/.config/ranger, ~/.config/alacritty, ~/.config/dunst, ~/.config/vifm, ~/.config/picom, ~/.config/polybar, ~/.i3, ~/.tmux.conf, ~/.tmux.reset.conf, ~/.config/sxiv, ~/.gitconfig, )

for i in "${config[@]}";do
	name=${i##*/}
	if [[ ${i::-1} =~ ".config" ]]; then
		if [[ -d ${i::-1} ]]; then
			cp -vr ${i::-1} $HOME/dotfile/.config/
		else
			cp ${i::-1} $HOME/dotfile/.config/${name::-1}
		fi
	else
		if [[ -d ${i::-1} ]]; then
			cp -vr ${i::-1} $HOME/dotfile/
		else
			cp ${i::-1} $HOME/dotfile/${name::-1}
		fi
	fi
done
cd $HOME/dotfile
git add .

echo "Enter the commit message:"
read message

if [[ -z "$message" ]];then
	git commit -m "backup"
else
	git commit -m "$message"
fi

git push origin main
clear
echo "Backup success!!"

