#!/usr/bin/env bash

RG_PREFIX="fd --follow -t d --color=always --hidden --exclude .git"
INITIAL_QUERY="${*:-}"
IFS=: read -ra selected < <(
  FZF_DEFAULT_COMMAND="$RG_PREFIX . $HOME" \
  fzf --ansi \
	  --color "hl:-1:underline,hl+:-1:underline:reverse" \
	  --bind "ctrl-l:unbind(change,ctrl-l)+change-prompt(2. fzf> )+enable-search+clear-query" \
	  --prompt '1. fd> ' \
	  --delimiter : \
	  --preview 'bat --style=numbers --color=always --line-range :500 {}'\
	  --preview-window 'up,60%,border-bottom,+{2}+3/3,~3'
)
[ -n "${selected[0]}" ] && cd "${selected[0]}"
exec $SHELL
