#!/usr/bin/bash
function cleanup() {
    tput cnorm
}

trap cleanup EXIT

while true; do
#row=10
#col=$(( ($(tput cols) - ${#text}) / $#))
#tput clear
#tput cup $row $col
clear
for var in "$@"
do
	figlet -w $(tput cols) -c  -f 3d "$var" | lolcat
	tput civis
done;
sleep 3;
done;
tput cnorm
