#!/bin/bash
session=$(
	tmux ls | cut -d':' -f1 | fzf-tmux -p 50%,40% --preview '' \
		--border-label 'switch session' \
		--header 'Press CTRL-R to reload, CTRL-A to add' \
		--bind 'ctrl-a:execute(tmux new -s {q} -d )+reload(tmux ls | cut -d ":" -f1)' \
		--bind 'ctrl-r:reload(tmux ls | cut -d ":" -f1)'
) && tmux switch-client -t "$session" || true
