#!/bin/bash
tmux list-windows | awk -F ' ' '{ print $2 }' |
	sed 's/[^a-zA-Z0-9]$//' |
	sed -E 's/[*-]?Z$//' |
	fzf-tmux -p 50%,40% --preview '' \
		--border-label 'switch windown' |
	xargs tmux select-window -t
