[[manager.prepend_keymap]]
on = "!"
run = 'shell "$SHELL" --block'
desc = "Open shell here"

[[manager.prepend_keymap]]
on = ["g", "r"]
run = '''
	shell 'ya emit cd "$(git rev-parse --show-toplevel)"'
'''
