add_newline = false

[line_break]
disabled = true

[character]
success_symbol = "[](bold green)[](bold red)[](bold blue)"
error_symbol = "[✗](bold red) "
vicmd_symbol = "[V](bold green) "

[python]
symbol = ' '

[directory]
truncation_symbol = "…/"
style = "bold #26b846"

[git_branch]
symbol = "[ ](bold #ef3c40)"
style = "bold #55a630"

[git_status]
format = "[$all_status$ahead_behind](bold red) "

#status
untracked = "[ untracked ](bold #FF990D)"
modified = "[ modified ](bold #FF990D)"
deleted = "[✘ deleted ](bold red)"
renamed = " renamed "

staged = "[ stage ](bold #FEDE00)"

#ahead_behind
ahead = "[ ](bold green)"
behind = "[ ](bold green)"

[username]
style_user = "#118ab2 bold"
style_root = "red bold"
format = "[](#e9f0fc)[ $user]($style) "
disabled = false
show_always = true

