add_newline = true
command_timeout = 1000

[character]
success_symbol = "[](bold green)[](bold red)[](bold blue)"
error_symbol = "[✗](bold red) "
vicmd_symbol = "[V](bold green) "

[python]
symbol = ' '

[directory]
# truncation_symbol = "…/"
# style = "bold #26b846"

[git_branch]
symbol = "[ ](bold #ef3c40)"
# style = "bold #55a630"

[git_status]
format = "[$all_status$ahead_behind](bold red) "

#status
untracked = "[ ](bold bright-red)"
modified = "[ ](bold #fe8019)"
deleted = "[✘ ](bold red)"
renamed = "[ ](bold #fe8019)"

staged = "[ ](bold green)"

#ahead_behind
ahead = "[ ](bold green)"
behind = "[ ](bold green)"

# [username]
# style_user = "#118ab2 bold"
# style_root = "red bold"
# format = "[$user]($style) "
# disabled = false
# show_always = true

